### ISSUE TITLE
Add support for HMAC512 JWT

### ISSUE THREAD

**Issue by hoerup** [hashicorp/vault-plugin-auth-jwt#111]
<strike>To be honest I couldn't figure out if HMAC + pre-shared secret is supported but poorly documented or just not supported yet ?</strike>

Please add support HMAC + pre-shared secret tokens

**Comment by swenson** [comment]
Hi,

Thanks for bringing this up.

In general, we can't support HS256/HS384/HS512 for the JWT plugin because there isn't an easy, secure, standard way to configure it.

Generally when configuring the JWT plugin, you specify a set of public keys, which are safe to share.

If we allowed shared symmetric secrets, you'd have to specify them **in plaintext** as part of the configuration of the plugin, which we aren't eager to support. The two alternatives would be to generate the symmetric shared secret inside Vault (probably not what anyone wants), or to wrap them with, for example, an RSA wrapping key, which isn't something widely used for HMAC shared secrets (unless I am wrong).

So, for now, I don't think we can support this feature. Sorry!
