### ISSUE TITLE
realm_access claim could not be converted to string list

### ISSUE THREAD

**Issue by avoidik** [hashicorp/vault-plugin-auth-jwt#9]
hi,

could you please help me to set `groups_claim` parameter for role? 

I've got error when I tried to set it to `groups_claim=realm_access`

```
* "realm_access" claim could not be converted to string list
```

my token has the following:

```
  "realm_access": {
    "roles": [
      "aaa",
      "bbb"
    ]
  },
```

**Comment by avoidik** [comment]
is there are any method to split `groups_claim` parameter to deliver only resulting list of strings, for example `groups_claim=realm_access/roles`?

```
* "realm_access/roles" claim not found in token
```

**Comment by jefferai** [comment]
No, there is not. I don't really know what the way forward here would be. I'm not aware of any character that can't be used in a claim name, which means there isn't any obvious delimiter.

I would suggest that you see if the JWT provider can put `roles` at the top level. The only documentation I can find that mentions `realm_access` suggests that the only thing that ever lives inside it is `roles`.

It looks like keycloak is aware of this kind of issue -- see https://issues.jboss.org/browse/KEYCLOAK-6884

**Comment by jdelic** [comment]
That there is no obvious delimiter doesn't mean that Vault couldn't for example define `.`  to be the delimiter and then also define escaping rules. For example `groups_claim=realm_access.roles` vs. `groups_claim=realm_access\.roles`. It sounds quite useful to me to be able to address nested objects in the claims.

**Comment by Trois-Six** [comment]
A workaround for this : inside Keycloak, select the client, then go to Mappers, then create a Protocol Mapper named roles. Your group claims will be available in the "roles" key and in the "realms_access.roles" key inside your access_token. So you can use group_claim="roles" in your jwt role inside Vault instead of group_claim="realms_access.roles" which is not working because of the nested dict.

**Comment by jefferai** [comment]
Just putting some thoughts down:

One of the potential issues with delimiters at a role level is whether they might only be valid for some claims and for other claims actually cause problems. One way to handle this might be to allow delimiters to be specified as part of a given claim value, so for groups claim it could be `groups_claim=.;realm_access.roles`

This can still be an issue if a delimiter needs to only nest one level and then stop, e.g. if a key name can *also* have a `.` in it, since that may make sense for some schema that we simply don't know. There could also be a depth parameter, e.g. `groups_claim=.;2;realm_access.roles`.

This also presupposes that semicolons are not used anywhere...

**Comment by jefferai** [comment]
@avoidik If you can take a look (or even better, test!) #15, basically it allows you to specify a string of delimiters. So in your case, you'd specify `groups_claim` to be `realm_access.roles` and set the `groups_claim_delimiter_pattern` to be `.`. But it would support things like `_.` which would then expect something like:
```
  "realm": {
    "access": {
      "roles": [
        "aaa",
        "bbb"
      ]
    }
  }
```

**Comment by jefferai** [comment]
@jdelic @Trois-Six same query/request for testing :-)

**Comment by avoidik** [comment]
@jefferai I've tested and it worked. I was able to authenticate with JWT token and then using the Identity Group Alias assign the policy to a requester. When it's planned to be released? Could please put a version tag :)

**Comment by jefferai** [comment]
It'll be released with the next beta of vault.

**Comment by Leletir** [comment]
Hello, first of all, thanks for your work !!

I'm trying to use keycloak for authentification against the vault. Reading the issue, I'm getting lost, which Auth backend do I have to use oidc or jwt ?

Thank you for your help.
